### PR TITLE
Add the sh extension to the SSH_KeyGen file

### PR DESCRIPTION
**Pull request by timotheeMM**
I resolved this issue : #1. :blush:

### CODE REVIEW

**Comment by 6a6ak** [comment]
👋 Hey timotheeMM,

I hope you're doing well! First of all, I'd like to thank you for taking the time to contribute to. Open source thrives on the collective effort of contributors like you, and every bit helps, big or small. 🌟
I wanted to share an exciting initiative I'm working on,
It's an SSH key-based login mechanism that associates an email with each key, making it easier to manage and identify keys. The keyword for adding an email identifier during the SSH key generation process is -C. I think your skills could really help push this project forward, and I'd love for you to be a part of it.

So, are you interested in diving deeper into this? Your expertise would be invaluable, and I'm eager to see how much farther we can take this project with your help.

**Comment by timotheeMM** [comment]
Hello and thank you for your very nice message :blush:. Unfortunately, I have no experience in shell language or SSH protocol. I tried to solve this issue because it was quite simple, and because I’m new to GitHub and I wanted to make my first pull request. Sorry, I can’t help you anymore :cry:.

**Comment by 6a6ak** [comment]
@timotheeMM 
Hello dear friend,

Your acknowledgment of not knowing something is not a sign of unprofessionalism; it's a sign of your bravery. I'm not that strong either and am currently working alone on an island. So far, no one has even looked at my codes. It's extremely satisfying for me if someone uses my code, or if I can solve someone's problem. If you're interested in working together, we can collaborate on any topic that interests us, regardless of what it might be. The sense of collaboration multiplies motivation. If you're interested, you can message me on LinkedIn, which is on my page, so we can solve any problem, no matter how small or large it is. :)

**Comment by timotheeMM** [comment]
Hello @6a6ak, you convinced me, I will take this opportunity to learn about the topics covered by this project.
PS: I am French, so if there are some errors in my English, don’t worry.

**Pull request merged**
